# Generated by Django 3.1.5 on 2021-01-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_auto_20210112_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(default='Descricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='ingredientes',
            field=models.CharField(default='Pao, Queijo, Presunto', max_length=200),
            preserve_default=False,
        ),
    ]
